### ISSUE TITLE
No Licence text is provided

### ISSUE THREAD

**Issue by psnx** [udacity/DevOps_Microservices#8]
In a nutshell from https://opensource.guide/legal/

> _Why do people care so much about the legal side of open source?_
Glad you asked! When you make a creative work (such as writing, graphics, or code), that work is under **exclusive copyright** by default. That is, the law assumes that as the author of your work, you have a say in what others can do with it.

This theoretically means that no one (including us, your students) can use your code in their own work.

**Comment by SudKul** [comment]
Thanks, @psnx for pointing this out. 
We have now added the License here: https://github.com/udacity/DevOps_Microservices/blob/master/LICENSE
